[package]
name = "punjs"
version = "0.0.0"
authors = ["Pekka Enberg"]
edition = "2021"
default-run = "punjs"

[[bin]]
name = "punjs"
path = "main.rs"

[dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.22", features = [ "derive" ] }
rusty_jsc = { version = "0.1.0", path = "../../../" }
rusty_jsc_macros = { version = "0.1.0", path = "../../../macros" }
rusty_jsc_sys = { version = "0.1.0", path = "../../../sys" }
